name: cc
channels:
    - psi4/label/dev
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - psi4
    - dftd3    
    - gcp
    - xtb
    - xtb-python
    - pip:
      - scipy
      - pandas
      - matplotlib
      - sympy
      - pytest
      - ipython
      - more-itertools
      - natsort
      - black
      - flake8
      - mypy
      - isort
