name: psi4
channels:
    - conda-forge
    - psi4/label/dev
dependencies:
    - python=3.9
    - pip
    - psi4
    - dftd3    
    - gcp
    - pip:
      - cclib
      - geomeTRIC
      - matplotlib
      - more-itertools
      - natsort
      - pandas
      - pyberny
      - scipy
# Tools
      - black
      - flake8
      - ipython
      - isort
      - mypy
      - pytest
