name: qcarchive
channels:
    - conda-forge
    - psi4/label/dev
dependencies:
    - psi4
    - dftd3    
    - gcp
    - geomeTRIC
    - xtb
    - rdkit
    - pip
    - pip:
      - pyscf
      - pyberny
      - scipy
      - pandas
      - matplotlib
      - networkx
      - cclib
      - pytest
      - ipython
      - more-itertools
      - natsort
      - black
      - flake8
      - mypy
      - isort
