name: cc
channels:
    - conda-forge
    - psi4/label/dev
dependencies:
    - python=3.10
    - pip
    - psi4
    - dftd3    
    - gcp
    - xtb
    - pip:
      - matplotlib
      - more-itertools
      - natsort
      - pandas
      - pipx
      - scipy
# Tools
      - black
      - flake8
      - ipython
      - isort
      - mypy
      - pytest
