name: crest
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - pipx
    - crest
    - pip:
      - cclib
      - matplotlib
      - more-itertools
      - natsort
      - pandas
      - scipy
# Tools
      - black
      - ipython
      - isort
      - flake8
      - mypy
      - pytest
