name: crest
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - pipx
    - crest
    - pip:
      - cclib
      - matplotlib
      - more-itertools
      - natsort
      - pandas
      - scipy
      - sympy
# Tools
      - black
      - ipython
      - mypy
      - pytest
      - ruff
