name: p311
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - pip:
      - matplotlib
      - more-itertools
      - natsort
      - pandas
      - pipx
      - scipy
      - sklearn
# Tools
      - black
      - ipython
      - mypy
      - pytest
      - ruff
