name: psi4
channels:
    - conda-forge
    - psi4/label/dev
dependencies:
    - python=3.10
    - pip
    - pipx
    - psi4
    - dftd3    
    - gcp
    - pip:
      - cclib
      - geomeTRIC
      - matplotlib
      - more-itertools
      - natsort
      - pandas
      - pyberny
      - scipy
      - sympy
# Tools
      - black
      - ipython
      - mypy
      - pytest
      - ruff
