name: psi4
channels:
    - psi4/label/dev
    - conda-forge/label/libint_dev
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - pipx
    - dftd3
    - dftd4
    - gcp-correction
    - psi4
    - pip:
      - cclib
      - geomeTRIC
      - matplotlib
      - more-itertools
      - natsort
      - pandas
      - pyberny
      - scipy
      - sympy
# Tools
      - black
      - ipython
      - mypy
      - pytest
      - ruff
