name: qcarchive
channels:
    - conda-forge
    - psi4/label/dev
dependencies:
    - python=3.9
    - pip
    - pipx
    - psi4
    - dftd3    
    - gcp
    - geomeTRIC
    - xtb
    - rdkit
    - pip:
      - cclib
      - geometric
      - matplotlib
      - more-itertools
      - natsort
      - networkx
      - pandas
      - pyberny
      - pyscf
      - scipy
# Tools
      - black
      - flake8
      - ipython
      - isort
      - mypy
      - pytest
